#!/usr/bin/env python3
"""Emit the HUD's generated content from the design data.

Two files, one generator, one `--check`, because they are the same job: a player-visible string is
decided once in a CSV under docs/design/ and reaches the screen without anybody retyping it.

The interface names things by icon key and never by a string of its own: `docs/design/icon-keys.csv`
is the one place a player-visible name is decided, and the content wiki is built from it. This
generator turns the same file into `Assets/Odyssey/Hud/Registry.g.cs`, so the HUD reads the label
the wiki shows and a name the owner corrects in the CSV reaches the screen without anyone
retyping it. The output is GENERATED, never hand-edited, and checked in beside the wiki.

  * `docs/design/icon-keys.csv`      -> `Assets/Odyssey/Hud/Registry.g.cs`
  * `docs/design/colonist-names.csv` -> `Assets/Odyssey/Hud/ColonistNames.g.cs`

Usage:
    python3 tools/wiki/emit_labels.py            # write both generated files
    python3 tools/wiki/emit_labels.py --check    # exit 1 if either is stale; nothing written

Standard library only, so it runs in a container with no Unity. Files are opened as UTF-8
explicitly: Windows Python otherwise reads the CSV in cp1252 and every accented label comes out
wrong (docs/lessons.md, "PYTHONUTF8").
"""
from __future__ import annotations
import csv, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SOURCE = os.path.join("docs", "design", "icon-keys.csv")
OUT = os.path.join("Assets", "Odyssey", "Hud", "Registry.g.cs")

NAMES_SOURCE = os.path.join("docs", "design", "colonist-names.csv")
NAMES_OUT = os.path.join("Assets", "Odyssey", "Hud", "ColonistNames.g.cs")

# Namespaces whose description column the screen reads as well as its name. Only these, so the
# generated file does not carry seven hundred tooltip seeds nothing draws: a research project's
# description is the body of the Research tab's detail pane (docs/design/34-research-tab.md), and
# writing it in C# would be the second copy the registry exists to prevent.
DESCRIBED = ("ui.research.project", "ui.world")


def load_labels():
    with open(os.path.join(ROOT, SOURCE), encoding="utf-8", newline="") as f:
        rows = list(csv.DictReader(f))
    labels = {}
    descriptions = {}
    for row in rows:
        key, label = row["key"].strip(), row["label"].strip()
        if not key or not label:
            raise SystemExit(f"{SOURCE}: a row has an empty key or label: {row}")
        if key in labels:
            raise SystemExit(f"{SOURCE}: key {key} appears twice")
        labels[key] = label
        if row["namespace"].strip() in DESCRIBED:
            description = row["tooltip_seed"].strip()
            if not description:
                raise SystemExit(f"{SOURCE}: {key} is drawn with its description and has none")
            descriptions[key] = description
    return labels, descriptions


def cs_string(text):
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render(loaded):
    labels, descriptions = loaded
    lines = [
        "// <auto-generated>",
        f"// Generated by tools/wiki/emit_labels.py from {SOURCE.replace(os.sep, '/')}.",
        "// Do not edit: change the CSV and rerun the generator. `--check` is the commit gate.",
        "// </auto-generated>",
        "#nullable enable",
        "using System.Collections.Generic;",
        "",
        "namespace Odyssey.Hud",
        "{",
        "    /// <summary>",
        "    /// Every player-visible name, by icon key, as the naming registry decides it. The HUD",
        "    /// asks here rather than carrying a string of its own, so the screen and the content",
        "    /// wiki cannot disagree about what a thing is called.",
        "    /// </summary>",
        "    public static class Registry",
        "    {",
        "        public static readonly Dictionary<string, string> Labels = new Dictionary<string, string>",
        "        {",
    ]
    for key in sorted(labels):
        lines.append(f"            {{ {cs_string(key)}, {cs_string(labels[key])} }},")
    lines += [
        "        };",
        "",
        "        /// <summary>",
        "        /// The label for a key, or the key itself when the registry has no such entry: a",
        "        /// raw key on screen is a visible fault, a blank is a silent one.",
        "        /// </summary>",
        "        public static string Label(string key) =>",
        "            Labels.TryGetValue(key, out string? label) ? label : key;",
        "",
        "        /// <summary>",
        "        /// The description column, for the few namespaces whose description is drawn as",
        "        /// well as their name (emit_labels.py, DESCRIBED).",
        "        /// </summary>",
        "        public static readonly Dictionary<string, string> Descriptions = new Dictionary<string, string>",
        "        {",
    ]
    for key in sorted(descriptions):
        lines.append(f"            {{ {cs_string(key)}, {cs_string(descriptions[key])} }},")
    lines += [
        "        };",
        "",
        "        /// <summary>A key's description, or empty when the registry draws none for it.</summary>",
        "        public static string Describe(string key) =>",
        "            Descriptions.TryGetValue(key, out string? text) ? text : string.Empty;",
        "    }",
        "}",
        "",
    ]
    return "\n".join(lines)


def load_names():
    """Every colonist given name, in the order the CSV lists them.

    The order is the file's and it is load-bearing: the pool is indexed by arithmetic, so
    reordering the CSV renames every colonist in every existing save. Add to the end.
    """
    with open(os.path.join(ROOT, NAMES_SOURCE), encoding="utf-8", newline="") as f:
        rows = list(csv.DictReader(f))
    names, seen = [], set()
    for row in rows:
        name = row["name"].strip()
        if not name:
            raise SystemExit(f"{NAMES_SOURCE}: a row has an empty name: {row}")
        if name in seen:
            raise SystemExit(f"{NAMES_SOURCE}: {name} appears twice, so two colonists would share it")
        if row["gender"].strip() not in ("m", "f", "n"):
            raise SystemExit(f"{NAMES_SOURCE}: {name} has gender {row['gender']!r}, not m/f/n")
        seen.add(name)
        names.append((name, row["gender"].strip()))
    if not names:
        raise SystemExit(f"{NAMES_SOURCE}: the pool is empty")
    return names


def render_names(rows):
    names = [n for n, _ in rows]
    genders = [g for _, g in rows]
    lines = [
        "// <auto-generated>",
        f"// Generated by tools/wiki/emit_labels.py from {NAMES_SOURCE.replace(os.sep, '/')}.",
        "// Do not edit: change the CSV and rerun the generator. `--check` is the commit gate.",
        "// </auto-generated>",
        "#nullable enable",
        "",
        "namespace Odyssey.Hud",
        "{",
        "    /// <summary>",
        "    /// The colonist given-name pool, as the naming CSV decides it.",
        "    ///",
        "    /// <para><b>A static array of interned literals, and that is the whole performance",
        "    /// story.</b> Naming a colonist is one index into this and no parsing, no file read, no",
        "    /// dictionary and no allocation — the strings are in the assembly's constant pool and",
        "    /// the array is built once by the static constructor. <c>ColonistNames.Of</c> is called",
        "    /// per figure per frame by the roster and the inspect header, so it has to cost",
        "    /// nothing.</para>",
        "    ///",
        "    /// <para><b>The order is the CSV's and it is load-bearing.</b> A colonist's name is",
        "    /// this array indexed by arithmetic on a saved seed, so reordering the CSV renames",
        "    /// every colonist in every existing save. Add to the end; never sort.</para>",
        "    ///",
        "    /// <para><b>Gender is emitted; register is not.</b> Gender picks which bodies and",
        "    /// which hair a colonist may be dealt (<c>docs/design/29-modular-colonists.md</c>), so",
        "    /// it is read by the game and belongs here. Register is still a column nothing reads,",
        "    /// and a generated constant nothing reads is the artefact that misleads the next",
        "    /// session. The wiki shows both so the owner can correct them.</para>",
        "    /// </summary>",
        "    public static class ColonistNamePool",
        "    {",
        f"        /// <summary>{len(names)} names, in CSV order.</summary>",
        "        public static readonly string[] Names =",
        "        {",
    ]

    # Eight to a line: short enough to read a diff, long enough not to be 244 lines.
    for i in range(0, len(names), 8):
        row = ", ".join(cs_string(n) for n in names[i:i + 8])
        lines.append(f"            {row},")

    lines += [
        "        };",
        "",
        "        /// <summary>",
        f"        /// The gender of each name, in the same order: {len(names)} entries, one per",
        "        /// <see cref=\"Names\"/> entry and the same length by construction.",
        "        ///",
        "        /// <para><c>m</c>, <c>f</c> or <c>n</c>. <c>n</c> is a real value and not a",
        "        /// fallback: a neutral name draws its body and hair from both pools.</para>",
        "        /// </summary>",
        "        public static readonly char[] Genders =",
        "        {",
    ]

    # Sixteen to a line: a char is a quarter the width of a name.
    for i in range(0, len(genders), 16):
        row = ", ".join("'" + g + "'" for g in genders[i:i + 16])
        lines.append(f"            {row},")

    lines += [
        "        };",
        "    }",
        "}",
        "",
    ]
    return chr(10).join(lines)


def main(argv=None):
    argv = sys.argv[1:] if argv is None else argv
    check = "--check" in argv

    outputs = [
        (OUT, render(load_labels())),
        (NAMES_OUT, render_names(load_names())),
    ]

    stale = 0
    for out, body in outputs:
        path = os.path.join(ROOT, out)

        if check:
            current = None
            if os.path.exists(path):
                with open(path, encoding="utf-8") as f:
                    current = f.read()
            if current != body:
                print(f"{out} is stale. Run: python3 tools/wiki/emit_labels.py")
                stale = 1
            else:
                print(f"ok: {out} is current ({body.count(chr(10))} lines)")
            continue

        with open(path, "w", encoding="utf-8") as f:
            f.write(body)
        print(f"ok: wrote {out}")

    return stale


if __name__ == "__main__":
    sys.exit(main())
