#!/usr/bin/env python3
"""Emit the HUD's label registry from the design data.

The interface names things by icon key and never by a string of its own: `docs/design/icon-keys.csv`
is the one place a player-visible name is decided, and the content wiki is built from it. This
generator turns the same file into `Assets/Odyssey/Hud/Registry.g.cs`, so the HUD reads the label
the wiki shows and a name the owner corrects in the CSV reaches the screen without anyone
retyping it. The output is GENERATED, never hand-edited, and checked in beside the wiki.

Usage:
    python3 tools/wiki/emit_labels.py            # write Assets/Odyssey/Hud/Registry.g.cs
    python3 tools/wiki/emit_labels.py --check    # exit 1 if the file is stale; nothing written

Standard library only, so it runs in a container with no Unity. Files are opened as UTF-8
explicitly: Windows Python otherwise reads the CSV in cp1252 and every accented label comes out
wrong (docs/lessons.md, "PYTHONUTF8").
"""
from __future__ import annotations
import csv, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SOURCE = os.path.join("docs", "design", "icon-keys.csv")
OUT = os.path.join("Assets", "Odyssey", "Hud", "Registry.g.cs")


def load_labels():
    with open(os.path.join(ROOT, SOURCE), encoding="utf-8", newline="") as f:
        rows = list(csv.DictReader(f))
    labels = {}
    for row in rows:
        key, label = row["key"].strip(), row["label"].strip()
        if not key or not label:
            raise SystemExit(f"{SOURCE}: a row has an empty key or label: {row}")
        if key in labels:
            raise SystemExit(f"{SOURCE}: key {key} appears twice")
        labels[key] = label
    return labels


def cs_string(text):
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render(labels):
    lines = [
        "// <auto-generated>",
        f"// Generated by tools/wiki/emit_labels.py from {SOURCE.replace(os.sep, '/')}.",
        "// Do not edit: change the CSV and rerun the generator. `--check` is the commit gate.",
        "// </auto-generated>",
        "#nullable enable",
        "using System.Collections.Generic;",
        "",
        "namespace Odyssey.Hud",
        "{",
        "    /// <summary>",
        "    /// Every player-visible name, by icon key, as the naming registry decides it. The HUD",
        "    /// asks here rather than carrying a string of its own, so the screen and the content",
        "    /// wiki cannot disagree about what a thing is called.",
        "    /// </summary>",
        "    public static class Registry",
        "    {",
        "        public static readonly Dictionary<string, string> Labels = new Dictionary<string, string>",
        "        {",
    ]
    for key in sorted(labels):
        lines.append(f"            {{ {cs_string(key)}, {cs_string(labels[key])} }},")
    lines += [
        "        };",
        "",
        "        /// <summary>",
        "        /// The label for a key, or the key itself when the registry has no such entry: a",
        "        /// raw key on screen is a visible fault, a blank is a silent one.",
        "        /// </summary>",
        "        public static string Label(string key) =>",
        "            Labels.TryGetValue(key, out string? label) ? label : key;",
        "    }",
        "}",
        "",
    ]
    return "\n".join(lines)


def main(argv=None):
    argv = sys.argv[1:] if argv is None else argv
    check = "--check" in argv
    body = render(load_labels())
    path = os.path.join(ROOT, OUT)

    if check:
        current = None
        if os.path.exists(path):
            with open(path, encoding="utf-8") as f:
                current = f.read()
        if current != body:
            print(f"{OUT} is stale. Run: python3 tools/wiki/emit_labels.py")
            return 1
        print(f"ok: {OUT} is current ({body.count(chr(10))} lines)")
        return 0

    with open(path, "w", encoding="utf-8") as f:
        f.write(body)
    print(f"ok: wrote {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
