#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Text;
using Odyssey.Presentation.Rendering;
using Odyssey.Presentation.World;
using UnityEditor;
using UnityEngine;

namespace Odyssey.EditorTools
{
    /// <summary>
    /// Measure every weapon mesh as a stack of boxes (<see cref="WeaponProfile"/>) and write the
    /// numbers into <c>Assets/Odyssey/Presentation/World/WeaponProfiles.g.cs</c> (design 33 §9c).
    ///
    /// <para>The meshes are not marked readable, so a player cannot measure them; the editor can,
    /// and the sheath fit needs more than their bounds. <c>WeaponProfileTests</c> fails when the
    /// table and the meshes disagree — run this again then.</para>
    ///
    /// <para><c>scripts/unity.sh exec Odyssey.EditorTools.WeaponProfileBake.Run</c>.</para>
    /// </summary>
    public static class WeaponProfileBake
    {
        public const string OutputPath = "Assets/Odyssey/Presentation/World/WeaponProfiles.g.cs";

        /// <summary>The weapons' catalogue rows: every prop a figure can hold at the hip.</summary>
        public static readonly string[] Rows =
        {
            ModuleIds.ItemBat, ModuleIds.ItemCrowbar, ModuleIds.ItemMachete, ModuleIds.ItemArcBlade,
            ModuleIds.ItemPistol,
        };

        [MenuItem("Odyssey/Presentation/Bake weapon profiles")]
        public static void RunFromMenu() => Bake(false);

        public static void Run() => Bake(Application.isBatchMode);

        static void Bake(bool exitWhenDone)
        {
            int exitCode = 0;
            try
            {
                var catalogue = AssetDatabase.LoadAssetAtPath<ModuleCatalogue>(PlayScene.CataloguePath);
                if (catalogue == null) throw new InvalidOperationException("no catalogue");

                var profiles = new SortedDictionary<string, WeaponProfile>(StringComparer.Ordinal);
                foreach (string id in Rows)
                {
                    GameObject? prefab = catalogue.Find(id)?.prefab;
                    if (prefab == null) throw new InvalidOperationException($"{id} has no art here: bake where the packs are");
                    foreach (MeshFilter filter in prefab.GetComponentsInChildren<MeshFilter>(includeInactive: true))
                    {
                        Mesh? mesh = filter.sharedMesh;
                        if (mesh == null || profiles.ContainsKey(mesh.name)) continue;
                        WeaponProfile? profile = WeaponProfile.Measure(mesh.vertices, mesh.triangles);
                        if (profile != null) profiles[mesh.name] = profile;
                    }
                }

                File.WriteAllText(Path.GetFullPath(OutputPath), Emit(profiles).Replace("\n", "\r\n"));
                AssetDatabase.ImportAsset(OutputPath);
                Debug.Log($"[WeaponProfiles] wrote {profiles.Count} meshes to {OutputPath}: {string.Join(", ", profiles.Keys)}");
            }
            catch (Exception e)
            {
                Debug.LogError("[WeaponProfiles] " + e);
                exitCode = 1;
            }
            finally
            {
                if (exitWhenDone) EditorApplication.Exit(exitCode);
            }
        }

        static string Emit(SortedDictionary<string, WeaponProfile> profiles)
        {
            var text = new StringBuilder();
            text.Append("// <auto-generated>\n");
            text.Append("// Written by Odyssey.EditorTools.WeaponProfileBake.Run from the weapon meshes. Do not edit:\n");
            text.Append("// run `scripts/unity.sh exec Odyssey.EditorTools.WeaponProfileBake.Run` instead.\n");
            text.Append("// </auto-generated>\n");
            text.Append("#nullable enable\n");
            text.Append("using System.Collections.Generic;\n\n");
            text.Append("namespace Odyssey.Presentation.World\n{\n");
            text.Append("    public static partial class WeaponProfiles\n    {\n");
            text.Append("        static readonly Dictionary<string, WeaponProfile> Table = new Dictionary<string, WeaponProfile>\n        {\n");
            foreach (KeyValuePair<string, WeaponProfile> pair in profiles)
            {
                WeaponProfile p = pair.Value;
                text.Append("            [\"").Append(pair.Key).Append("\"] = new WeaponProfile(")
                    .Append(p.Axis).Append(", ").Append(F(p.Min)).Append(", ").Append(F(p.Max)).Append(", new[]\n            {\n");
                for (int s = 0; s < WeaponProfile.Slices; s++)
                {
                    text.Append("                ");
                    for (int k = 0; k < 4; k++) text.Append(F(p.Extents[s * 4 + k])).Append(k < 3 ? ", " : ",\n");
                }
                text.Append("            }),\n");
            }
            text.Append("        };\n    }\n}\n");
            return text.ToString();
        }

        static string F(float value) => value.ToString("0.#####", CultureInfo.InvariantCulture) + "f";
    }
}
