#nullable enable
using System;
using System.Collections.Generic;
using UnityEngine;

namespace Odyssey.Presentation.Audio
{
    /// <summary>
    /// The table of every sound the game can play: what clips stand in for it, which bus it
    /// rides, how loud, how far it carries, how often it may repeat.
    ///
    /// A ScriptableObject for the same reason <c>ModuleCatalogue</c> is: the id-to-asset mapping
    /// is data, it has to be resolvable without Synty or any licensed pack present, and the asset
    /// is generated by editor tooling rather than hand-authored (<c>AudioSetup</c> writes it from
    /// the placeholder clips today; when real audio is licensed, the same asset is regenerated or
    /// re-pointed and no code changes). A clone without the asset gets silence and a working game
    /// — the same bargain every other piece of presentation art makes.
    ///
    /// The variance fields are not decoration. A sound played identically every time is
    /// recognisably the same sample within three or four plays; ±8% pitch and ±12% amplitude on
    /// the short work sounds is the difference between a colony at work and a colony of
    /// typewriters.
    /// </summary>
    [CreateAssetMenu(menuName = "Odyssey/Audio Catalogue", fileName = "AudioCatalogue")]
    public sealed class AudioCatalogue : ScriptableObject
    {
        /// <summary>
        /// One playable sound. <see cref="Clips"/> is a set and not a clip: a sound with variants
        /// picks one at random per play, which halves the perceived repetition on its own before
        /// the pitch variance does anything.
        /// </summary>
        [Serializable]
        public sealed class SoundDef
        {
            public string Id = "";

            [Tooltip("The variants, one picked per play. May be empty: the sound then plays nothing.")]
            public AudioClip[] Clips = Array.Empty<AudioClip>();

            public SoundBus Bus = SoundBus.Effects;

            [Tooltip("Loudness before variance and bus volume. Most sounds ship below 1: the mix is set here, not at the bus.")]
            [Range(0f, 1f)] public float Volume = 0.9f;

            [Tooltip("± amplitude per play, as a fraction of Volume.")]
            [Range(0f, 0.4f)] public float VolumeVariance = 0.12f;

            [Tooltip("± pitch per play. 0.08 is just past the threshold of noticing.")]
            [Range(0f, 0.4f)] public float PitchVariance = 0.08f;

            [Tooltip("2D to 3D. Work sounds are 3D (they are somewhere); alerts are 2D (they are nowhere, they are for you).")]
            [Range(0f, 1f)] public float SpatialBlend = 1f;

            [Tooltip("Metres at which the sound is at full volume. Inside this ring, distance does not attenuate.")]
            public float MinDistance = 6f;

            [Tooltip("Metres at which the sound is gone. Also the cull range: further than this and it is not played at all.")]
            public float MaxDistance = 55f;

            [Tooltip("Unity voice priority, 0 first served. Alerts are near 0; ambience is near 256.")]
            [Range(0, 256)] public int Priority = 128;

            [Tooltip("Seconds between plays of this sound, whoever plays it. A colony of five woodcutters is one chop-line, not five.")]
            [Range(0f, 2f)] public float Cooldown = 0.12f;
        }

        /// <summary>One looping environmental bed, of which exactly one voice ever exists. Its
        /// volume is not in the table because it is not a property of the sound: it is how much
        /// of that environment the camera is presently sitting in, measured every frame by
        /// <see cref="AmbienceProbe"/>.</summary>
        [Serializable]
        public sealed class AmbienceDef
        {
            public string Id = "";
            public AudioClip? Clip;

            [Range(0f, 1f)] public float Volume = 0.8f;

            [Tooltip("Seconds the bed takes to reach a new intensity. Slow: environment does not snap.")]
            [Range(0.2f, 10f)] public float FadeSeconds = 2.5f;

            [Tooltip("Metres of full-volume radius around the bed's centroid. The bed is a place, not a fog.")]
            public float MinDistance = 30f;

            public float MaxDistance = 110f;
        }

        /// <summary>
        /// One looping track bound to the clock phase it plays in.
        ///
        /// Used for the music and for the outdoor ambience bed, which are the same shape of
        /// thing — a loop per phase, crossfaded when the phase turns — differing only in which
        /// bus they ride and how loud they sit.
        /// </summary>
        [Serializable]
        public sealed class PhaseTrackDef
        {
            public MusicPhase Phase;
            public AudioClip? Clip;

            [Range(0f, 1f)] public float Volume = 0.5f;

            [Tooltip("Seconds of crossfade between phases.")]
            [Range(0.5f, 10f)] public float FadeSeconds = 3f;
        }

        public List<SoundDef> Sounds = new();
        public List<AmbienceDef> Ambience = new();
        public List<PhaseTrackDef> Music = new();

        /// <summary>The outdoor bed, one track per phase: what the world sounds like when you
        /// are standing in it, as against the water bed, which is what is near you.</summary>
        public List<PhaseTrackDef> Outdoor = new();

        public SoundDef? Find(string id)
        {
            for (int i = 0; i < Sounds.Count; i++)
                if (string.Equals(Sounds[i].Id, id, StringComparison.Ordinal)) return Sounds[i];
            return null;
        }

        public AmbienceDef? FindAmbience(string id)
        {
            for (int i = 0; i < Ambience.Count; i++)
                if (string.Equals(Ambience[i].Id, id, StringComparison.Ordinal)) return Ambience[i];
            return null;
        }

        public PhaseTrackDef? FindMusic(MusicPhase phase) => Find(Music, phase);

        public PhaseTrackDef? FindOutdoor(MusicPhase phase) => Find(Outdoor, phase);

        static PhaseTrackDef? Find(List<PhaseTrackDef> tracks, MusicPhase phase)
        {
            for (int i = 0; i < tracks.Count; i++)
                if (tracks[i].Phase == phase) return tracks[i];
            return null;
        }
    }
}
