// <auto-generated>
// Generated by tools/wiki/emit_labels.py from docs/design/colonist-names.csv.
// Do not edit: change the CSV and rerun the generator. `--check` is the commit gate.
// </auto-generated>
#nullable enable

namespace Odyssey.Hud
{
    /// <summary>
    /// The colonist given-name pool, as the naming CSV decides it.
    ///
    /// <para><b>A static array of interned literals, and that is the whole performance
    /// story.</b> Naming a colonist is one index into this and no parsing, no file read, no
    /// dictionary and no allocation — the strings are in the assembly's constant pool and
    /// the array is built once by the static constructor. <c>ColonistNames.Of</c> is called
    /// per figure per frame by the roster and the inspect header, so it has to cost
    /// nothing.</para>
    ///
    /// <para><b>The order is the CSV's and it is load-bearing.</b> A colonist's name is
    /// this array indexed by arithmetic on a saved seed, so reordering the CSV renames
    /// every colonist in every existing save. Add to the end; never sort.</para>
    ///
    /// <para><b>Gender is emitted; register is not.</b> Gender picks which bodies and
    /// which hair a colonist may be dealt (<c>docs/design/29-modular-colonists.md</c>), so
    /// it is read by the game and belongs here. Register is still a column nothing reads,
    /// and a generated constant nothing reads is the artefact that misleads the next
    /// session. The wiki shows both so the owner can correct them.</para>
    /// </summary>
    public static class ColonistNamePool
    {
        /// <summary>240 names, in CSV order.</summary>
        public static readonly string[] Names =
        {
            "James", "Emma", "Liam", "Olivia", "Noah", "Sophia", "Oliver", "Ava",
            "Elijah", "Isabella", "William", "Mia", "Lucas", "Charlotte", "Benjamin", "Amelia",
            "Henry", "Harper", "Evelyn", "Mason", "Abigail", "Michael", "Emily", "Ethan",
            "Ella", "Daniel", "Elizabeth", "Jonah", "Camila", "Logan", "Luna", "Jackson",
            "Sofia", "Levi", "Avery", "Scarlett", "Jack", "Eleanor", "Owen", "Madison",
            "Theodore", "Layla", "Samuel", "Penelope", "Joseph", "Chloe", "John", "Grace",
            "David", "Nora", "Luke", "Hazel", "Julian", "Zoey", "Dylan", "Riley",
            "Matthew", "Victoria", "Leo", "Lily", "Isaac", "Aurora", "Gabriel", "Violet",
            "Anthony", "Nova", "Jaxon", "Hannah", "Carter", "Emilia", "Thomas", "Stella",
            "Charles", "Maya", "Willow", "Caleb", "Addison", "Andrew", "Lucy", "Joshua",
            "Paisley", "Nathan", "Natalie", "Ryan", "Elena", "Adrian", "Naomi", "Christian",
            "Alice", "Aaron", "Sadie", "Eli", "Ruby", "Nolan", "Eva", "Hunter",
            "Ivy", "Silas", "Vesper", "Kael", "Wren", "Dax", "Juno", "Thorne",
            "Lyra", "Cassian", "Zephyr", "Mira", "Soren", "Nyx", "Bram", "Elio",
            "Riven", "Astrid", "Vance", "Freya", "Orson", "Talia", "Zane", "Corin",
            "Isla", "Malachi", "Sterling", "Calla", "Lucian", "Ren", "Maeve", "Jett",
            "Orion", "Nadia", "Desmond", "Faye", "Gareth", "Thea", "Knox", "Selene",
            "Rowan", "Evander", "Cleo", "Tobias", "Marlo", "Felix", "Zelda", "Alistair",
            "Rhiannon", "Griffin", "Sylvie", "Cade", "Ophelia", "Darian", "Iris", "Leland",
            "Petra", "Ronin", "Sabine", "Jasper", "Willa", "Stellan", "Greer", "Leander",
            "Mina", "Balthazar", "Lyall", "Anouk", "Cormac", "Elowen", "Kieran", "Delia",
            "Otto", "Saskia", "Declan", "Mara", "Gideon", "Thalia", "Idris", "Cassia",
            "Finnian", "Blythe", "Torin", "Gemma", "Nikolai", "Solana", "Beckett", "Verity",
            "Magnus", "Dahlia", "Emory", "Linnea", "Jude", "Zora", "Henrik", "Colette",
            "Rafe", "Paloma", "Bastian", "Fiona", "Wrenn", "Odile", "Kester", "Sable",
            "Fen", "Ilma", "Torv", "Tim", "Ben", "Simon", "Mike", "Weasel",
            "Jungle", "Diggy G", "Jesus", "Jimmy", "Karl", "Maston", "Tristan", "Dave",
            "Bingo", "Lucky G", "Pleb", "Jonny", "Johnny", "Bishop", "Pete", "Dwayne",
            "Mungo", "Treacle", "Sausage", "Gardino", "Gary", "Gazza", "Smithy", "Johno",
            "Spudgun", "Spud", "Tommy", "Preston", "Flower", "Holiday", "Bert", "Wade",
        };

        /// <summary>
        /// The gender of each name, in the same order: 240 entries, one per
        /// <see cref="Names"/> entry and the same length by construction.
        ///
        /// <para><c>m</c>, <c>f</c> or <c>n</c>. <c>n</c> is a real value and not a
        /// fallback: a neutral name draws its body and hair from both pools.</para>
        /// </summary>
        public static readonly char[] Genders =
        {
            'm', 'f', 'm', 'f', 'm', 'f', 'm', 'f', 'm', 'f', 'm', 'f', 'm', 'f', 'm', 'f',
            'm', 'f', 'f', 'm', 'f', 'm', 'f', 'm', 'f', 'm', 'f', 'm', 'f', 'm', 'f', 'm',
            'f', 'm', 'n', 'f', 'm', 'f', 'm', 'f', 'm', 'f', 'm', 'f', 'm', 'f', 'm', 'f',
            'm', 'f', 'm', 'f', 'm', 'f', 'm', 'n', 'm', 'f', 'm', 'f', 'm', 'f', 'm', 'f',
            'm', 'f', 'm', 'f', 'm', 'f', 'm', 'f', 'm', 'f', 'f', 'm', 'n', 'm', 'f', 'm',
            'f', 'm', 'f', 'm', 'f', 'm', 'f', 'm', 'f', 'm', 'f', 'm', 'f', 'm', 'f', 'm',
            'f', 'm', 'f', 'm', 'n', 'm', 'f', 'm', 'f', 'm', 'n', 'f', 'm', 'f', 'm', 'm',
            'n', 'f', 'm', 'f', 'm', 'f', 'm', 'n', 'f', 'm', 'm', 'f', 'm', 'n', 'f', 'm',
            'm', 'f', 'm', 'f', 'm', 'f', 'm', 'f', 'n', 'm', 'f', 'm', 'n', 'm', 'f', 'm',
            'f', 'm', 'f', 'm', 'f', 'm', 'f', 'm', 'f', 'm', 'f', 'm', 'f', 'm', 'n', 'm',
            'f', 'm', 'm', 'f', 'm', 'f', 'm', 'f', 'm', 'f', 'm', 'f', 'm', 'f', 'm', 'f',
            'm', 'n', 'm', 'f', 'm', 'f', 'm', 'f', 'm', 'f', 'n', 'f', 'm', 'f', 'm', 'f',
            'm', 'f', 'm', 'f', 'n', 'f', 'm', 'n', 'n', 'f', 'm', 'm', 'm', 'm', 'm', 'n',
            'n', 'n', 'm', 'm', 'm', 'm', 'm', 'm', 'n', 'n', 'n', 'm', 'm', 'm', 'm', 'm',
            'm', 'n', 'n', 'n', 'm', 'm', 'n', 'm', 'n', 'n', 'm', 'm', 'n', 'n', 'm', 'm',
        };
    }
}
