#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using Odyssey.Sim.Contracts;

namespace Odyssey.Hud
{
    /// <summary>One row of the World screen's site panel: a label key, and the value as drawn.</summary>
    public readonly struct WorldStat
    {
        public WorldStat(string labelKey, string value, bool numeric)
        {
            LabelKey = labelKey;
            Value = value;
            Numeric = numeric;
        }

        public readonly string LabelKey;
        public readonly string Value;

        /// <summary>A value with a figure in it, drawn in the mono face.</summary>
        public readonly bool Numeric;
    }

    /// <summary>
    /// The World screen's model (design 59 §9): the planet the seed makes, the site picked on it,
    /// whether a colony may land there and why not, and what the site panel says.
    ///
    /// <para><b>The planet is generated by a function handed in</b>, because the generator is the
    /// simulation's and this assembly cannot see it — the shape <see cref="ColonistSelect"/> already
    /// has. It is regenerated only when the seed changes, so the page repaints its one texture once
    /// per seed (P10).</para>
    /// </summary>
    public sealed class WorldChoice
    {
        public static readonly string[] HillKeys =
            { "ui.hills.flat", "ui.hills.rolling", "ui.hills.hilly", "ui.hills.mountainous", "ui.hills.sheer" };

        /// <summary>Every word the screen draws that is not a biome or a hill band.</summary>
        public static readonly string[] IconKeys =
        {
            "ui.world.title", "ui.world.subtitle", "ui.world.wraphint", "ui.world.zoomhint", "ui.world.random",
            "ui.world.next", "ui.world.legend", "ui.world.settleable", "ui.world.selectedsite", "ui.world.biome",
            "ui.world.hills", "ui.world.temperature", "ui.world.seasons", "ui.world.rainfall", "ui.world.latitude",
            "ui.world.tile", "ui.world.depth", "ui.world.unavailable", "ui.world.water", "ui.world.steep",
            "ui.world.foot", "ui.world.zoomin", "ui.world.zoomout", "ui.world.fit", "ui.world.north",
            "ui.world.south", "ui.world.mm", "ui.world.layers", "ui.world.to",
        };

        readonly SeedField _seed;
        readonly Func<uint, PlanetView> _generate;
        readonly Func<int, int> _random;
        uint _planetSeed;

        /// <param name="generate">The simulation's planet generator, for a seed.</param>
        /// <param name="random">Draws 0 up to n for Random site; the interface's own chance, since only the tile chosen reaches the simulation.</param>
        public WorldChoice(SeedField seed, Func<uint, PlanetView> generate, Func<int, int>? random = null)
        {
            _seed = seed ?? throw new ArgumentNullException(nameof(seed));
            _generate = generate ?? throw new ArgumentNullException(nameof(generate));
            var fallback = new Random();
            _random = random ?? (n => fallback.Next(n));
            _seed.Changed += Refresh;
        }

        /// <summary>The planet the seed in the box makes, or null before a usable seed has been seen.</summary>
        public PlanetView? Planet { get; private set; }

        /// <summary>The picked tile, or −1. Starts on the planet's suggested site.</summary>
        public int Selected { get; private set; } = -1;

        /// <summary>The tile under the pointer, or −1.</summary>
        public int Hovered { get; private set; } = -1;

        /// <summary>Raised when a new planet has been made: the page repaints its texture and its names.</summary>
        public event Action? PlanetChanged;

        /// <summary>Raised when the selection or the hover moves.</summary>
        public event Action? Changed;

        /// <summary>
        /// Make the planet for the seed in the box, if it is usable and not the one already made. The
        /// selection goes to the new planet's suggested site, so Next is always one press away.
        /// </summary>
        public void Refresh()
        {
            if (!_seed.Usable) return;
            if (Planet != null && _planetSeed == _seed.Seed) return;
            Planet = _generate(_seed.Seed);
            _planetSeed = _seed.Seed;
            Selected = Planet.SuggestedTile;
            Hovered = -1;
            PlanetChanged?.Invoke();
            Changed?.Invoke();
        }

        public void Select(int tile)
        {
            if (Planet == null || tile < 0 || tile >= Planet.TileCount || tile == Selected) return;
            Selected = tile;
            Changed?.Invoke();
        }

        public void Hover(int tile)
        {
            if (Planet == null) return;
            if (tile >= Planet.TileCount) tile = -1;
            if (tile == Hovered) return;
            Hovered = tile;
            Changed?.Invoke();
        }

        /// <summary>
        /// Another tile a colony could land on, never the one already picked. False when the planet
        /// has no other, which the generator's guarantee makes a planet of one Meadow tile.
        /// </summary>
        public bool SelectRandom()
        {
            if (Planet == null) return false;
            var candidates = new List<int>();
            for (int t = 0; t < Planet.TileCount; t++)
                if (t != Selected && Planet.Verdict(t) == SettleVerdict.Settleable) candidates.Add(t);
            if (candidates.Count == 0) return false;
            Select(candidates[_random(candidates.Count)]);
            return true;
        }

        /// <summary>Step the selection one hex (a <see cref="HexGrid"/> direction). Nothing off a pole.</summary>
        public void Move(int direction)
        {
            if (Planet == null || Selected < 0) return;
            int next = HexGrid.Neighbour(HexGrid.Column(Selected, Planet.Width), HexGrid.Row(Selected, Planet.Width),
                direction, Planet.Width, Planet.Height);
            if (next >= 0) Select(next);
        }

        /// <summary>Whether a colony may land on the picked tile.</summary>
        public SettleVerdict Verdict => Planet == null || Selected < 0 ? SettleVerdict.NotYetAvailable : Planet.Verdict(Selected);

        /// <summary>
        /// Next is live only on a settleable tile of the planet the box's seed makes — never on a planet
        /// left over from a seed the player has since typed over.
        /// </summary>
        public bool CanGoNext => Planet != null && _seed.Usable && _planetSeed == _seed.Seed
                                 && Selected >= 0 && Planet.Verdict(Selected) == SettleVerdict.Settleable;

        /// <summary>The site the colony lands on, or null while Next is not live.</summary>
        public SiteTile? Site => CanGoNext ? Planet!.Tile(Selected) : (SiteTile?)null;

        /// <summary>The world seed the site belongs to.</summary>
        public uint WorldSeed => _planetSeed;

        /// <summary>The registry key that heads the status box for a verdict.</summary>
        public static string VerdictKey(SettleVerdict verdict) => verdict switch
        {
            SettleVerdict.Settleable => "ui.world.settleable",
            SettleVerdict.OpenWater => "ui.world.water",
            SettleVerdict.TooSteep => "ui.world.steep",
            _ => "ui.world.unavailable",
        };

        /// <summary>
        /// The site panel's rows for a tile (the specification's list): biome, hills, mean
        /// temperature, the seasons from coldest to warmest month, rainfall, latitude and the tile's
        /// place — and the board's depth when a mountainous site deepens it.
        /// </summary>
        public static List<WorldStat> Stats(PlanetView planet, int tile, int chosenLayers = 16)
        {
            var rows = new List<WorldStat>();
            if (tile < 0 || tile >= planet.TileCount) return rows;

            HillBand hills = planet.HillsAt(tile);
            rows.Add(new WorldStat("ui.world.biome", Registry.Label(planet.BiomeAt(tile).LabelKey), false));
            rows.Add(new WorldStat("ui.world.hills", Registry.Label(HillKeys[(int)hills]), false));
            rows.Add(new WorldStat("ui.world.temperature", TemperatureLabels.Describe(planet.MeanTempC[tile]), true));

            if (planet.SeasonCurveC.Length > 0)
            {
                planet.SeasonRange(tile, out int coldest, out int warmest);
                rows.Add(new WorldStat("ui.world.seasons",
                    TemperatureLabels.Number(coldest) + " " + Registry.Label("ui.world.to") + " " + TemperatureLabels.Describe(warmest), true));
            }

            rows.Add(new WorldStat("ui.world.rainfall",
                planet.RainfallMm[tile].ToString("N0", CultureInfo.InvariantCulture) + " " + Registry.Label("ui.world.mm"), true));

            int latitude = planet.LatitudePerMille(tile);
            rows.Add(new WorldStat("ui.world.latitude",
                SiteRules.LatitudeDegrees(latitude).ToString(CultureInfo.InvariantCulture) + " "
                + Registry.Label(latitude >= 0 ? "ui.world.north" : "ui.world.south"), true));

            rows.Add(new WorldStat("ui.world.tile",
                HexGrid.Column(tile, planet.Width).ToString(CultureInfo.InvariantCulture) + ", "
                + HexGrid.Row(tile, planet.Width).ToString(CultureInfo.InvariantCulture), true));

            int layers = SiteRules.BoardLayers(chosenLayers, hills);
            if (layers != chosenLayers)
                rows.Add(new WorldStat("ui.world.depth",
                    layers.ToString(CultureInfo.InvariantCulture) + " " + Registry.Label("ui.world.layers"), true));
            return rows;
        }

        /// <summary>
        /// The setup page's read-only site line, for example "Meadow, Rolling, 53 N", with the depth
        /// added on a mountainous site.
        /// </summary>
        public static string SiteLine(PlanetView planet, int tile, int chosenLayers = 16)
        {
            if (tile < 0 || tile >= planet.TileCount) return string.Empty;
            HillBand hills = planet.HillsAt(tile);
            int latitude = planet.LatitudePerMille(tile);
            string line = Registry.Label(planet.BiomeAt(tile).LabelKey) + ", " + Registry.Label(HillKeys[(int)hills])
                          + ", " + SiteRules.LatitudeDegrees(latitude).ToString(CultureInfo.InvariantCulture) + " "
                          + Registry.Label(latitude >= 0 ? "ui.world.north" : "ui.world.south");
            int layers = SiteRules.BoardLayers(chosenLayers, hills);
            if (layers != chosenLayers)
                line += ", " + layers.ToString(CultureInfo.InvariantCulture) + " " + Registry.Label("ui.world.layers");
            return line;
        }
    }
}
