#nullable enable
using System.Collections.Generic;
using UnityEngine;

namespace Odyssey.Presentation.World
{
    /// <summary>
    /// A weapon mesh's shape as a stack of boxes along its long axis, measured in the editor and
    /// committed as numbers (design 33 §9c), because the meshes are not marked readable and a
    /// player cannot ask them.
    ///
    /// <para><b>Why a stack and not the bounds.</b> The bounds of a bat are as fat at the handle
    /// as at the barrel, and the bounds of a crowbar are as deep all the way down as its claw is at
    /// the top; a weapon fitted by its bounds against the hip hangs a handle's width or a claw's
    /// depth off the body, which is the gap the owner reported. A slice at a time, each box is
    /// only as big as the weapon is there.</para>
    ///
    /// <para><see cref="WeaponProfiles"/> holds the table, generated by
    /// <c>Odyssey.EditorTools.WeaponProfileBake</c> from the art; <c>WeaponProfileTests</c> fails
    /// when it no longer matches the meshes.</para>
    /// </summary>
    public sealed class WeaponProfile
    {
        /// <summary>How many slices a weapon is cut into along its long axis.</summary>
        public const int Slices = 32;

        /// <summary>The mesh-space axis the weapon is longest along: 0 x, 1 y, 2 z.</summary>
        public readonly int Axis;

        /// <summary>Where along <see cref="Axis"/> the mesh starts and ends, in mesh units.</summary>
        public readonly float Min, Max;

        /// <summary>
        /// Per slice, from <see cref="Min"/>: the least and greatest the mesh reaches on the next
        /// axis round, then on the one after (<c>(Axis + 1) % 3</c>, <c>(Axis + 2) % 3</c>); four
        /// numbers a slice, and a slice the mesh does not reach holds its neighbour's.
        /// </summary>
        public readonly float[] Extents;

        public WeaponProfile(int axis, float min, float max, float[] extents)
        {
            Axis = axis;
            Min = min;
            Max = max;
            Extents = extents;
        }

        /// <summary>Cut a mesh's triangles into the stack. Null for a mesh with no length.</summary>
        public static WeaponProfile? Measure(Vector3[] vertices, int[] triangles)
        {
            if (vertices.Length == 0 || triangles.Length < 3) return null;
            var bounds = new Bounds(vertices[0], Vector3.zero);
            for (int i = 1; i < vertices.Length; i++) bounds.Encapsulate(vertices[i]);
            Vector3 e = bounds.extents;
            int axis = e.x >= e.y && e.x >= e.z ? 0 : e.y >= e.z ? 1 : 2;
            int u = (axis + 1) % 3, v = (axis + 2) % 3;
            float min = bounds.min[axis], max = bounds.max[axis];
            float length = max - min;
            if (length <= 1e-5f) return null;

            var extents = new float[Slices * 4];
            var seen = new bool[Slices];
            for (int s = 0; s < Slices; s++)
            {
                extents[s * 4] = extents[s * 4 + 2] = float.PositiveInfinity;
                extents[s * 4 + 1] = extents[s * 4 + 3] = float.NegativeInfinity;
            }

            // The triangles cut at the slice spacing, so a long face spanning several slices
            // counts in each of them and not only at its corners.
            float step = length / Slices * 0.25f;
            for (int t = 0; t + 2 < triangles.Length; t += 3)
            {
                Vector3 a = vertices[triangles[t]], b = vertices[triangles[t + 1]], c = vertices[triangles[t + 2]];
                int nb = Mathf.Clamp(Mathf.CeilToInt((b - a).magnitude / step), 1, 256);
                int nc = Mathf.Clamp(Mathf.CeilToInt((c - a).magnitude / step), 1, 256);
                int n = Mathf.Max(nb, nc);
                for (int i = 0; i <= n; i++)
                {
                    for (int j = 0; i + j <= n; j++)
                    {
                        Vector3 p = a + (b - a) * (i / (float)n) + (c - a) * (j / (float)n);
                        int s = Mathf.Clamp(Mathf.FloorToInt((p[axis] - min) / length * Slices), 0, Slices - 1);
                        seen[s] = true;
                        extents[s * 4] = Mathf.Min(extents[s * 4], p[u]);
                        extents[s * 4 + 1] = Mathf.Max(extents[s * 4 + 1], p[u]);
                        extents[s * 4 + 2] = Mathf.Min(extents[s * 4 + 2], p[v]);
                        extents[s * 4 + 3] = Mathf.Max(extents[s * 4 + 3], p[v]);
                    }
                }
            }

            for (int s = 0; s < Slices; s++)
            {
                if (seen[s]) continue;
                int from = -1;
                for (int d = 1; d < Slices && from < 0; d++)
                {
                    if (s - d >= 0 && seen[s - d]) from = s - d;
                    else if (s + d < Slices && seen[s + d]) from = s + d;
                }
                if (from < 0) return null;
                for (int k = 0; k < 4; k++) extents[s * 4 + k] = extents[from * 4 + k];
            }
            return new WeaponProfile(axis, min, max, extents);
        }

        /// <summary>
        /// Points over the stack's surface, in world space through <paramref name="mesh"/> (the
        /// transform the mesh is drawn under), no further apart than <paramref name="spacing"/>
        /// metres: each slice's four sides, and its ends.
        /// </summary>
        public void AddPoints(Transform mesh, float spacing, List<Vector3> points)
        {
            int u = (Axis + 1) % 3, v = (Axis + 2) % 3;
            float slice = (Max - Min) / Slices;
            float scaleA = Scale(mesh, Axis), scaleU = Scale(mesh, u), scaleV = Scale(mesh, v);
            int na = Mathf.Clamp(Mathf.CeilToInt(slice * scaleA / spacing), 1, 64);
            for (int s = 0; s < Slices; s++)
            {
                float u0 = Extents[s * 4], u1 = Extents[s * 4 + 1], v0 = Extents[s * 4 + 2], v1 = Extents[s * 4 + 3];
                int nu = Mathf.Clamp(Mathf.CeilToInt((u1 - u0) * scaleU / spacing), 1, 64);
                int nv = Mathf.Clamp(Mathf.CeilToInt((v1 - v0) * scaleV / spacing), 1, 64);
                for (int i = 0; i <= na; i++)
                {
                    float along = Min + slice * (s + i / (float)na);
                    // The four sides.
                    for (int j = 0; j <= nu; j++)
                    {
                        float a = Mathf.Lerp(u0, u1, j / (float)nu);
                        points.Add(At(mesh, along, a, v0, u, v));
                        points.Add(At(mesh, along, a, v1, u, v));
                    }
                    for (int j = 0; j <= nv; j++)
                    {
                        float b = Mathf.Lerp(v0, v1, j / (float)nv);
                        points.Add(At(mesh, along, u0, b, u, v));
                        points.Add(At(mesh, along, u1, b, u, v));
                    }
                }
                // The ends of the stack, where the butt and the tip are.
                if (s != 0 && s != Slices - 1) continue;
                float end = s == 0 ? Min : Max;
                for (int j = 0; j <= nu; j++)
                    for (int k = 0; k <= nv; k++)
                        points.Add(At(mesh, end, Mathf.Lerp(u0, u1, j / (float)nu), Mathf.Lerp(v0, v1, k / (float)nv), u, v));
            }
        }

        Vector3 At(Transform mesh, float along, float a, float b, int u, int v)
        {
            Vector3 p = default;
            p[Axis] = along;
            p[u] = a;
            p[v] = b;
            return mesh.TransformPoint(p);
        }

        static float Scale(Transform at, int axis)
        {
            Vector3 unit = Vector3.zero;
            unit[axis] = 1f;
            return at.TransformVector(unit).magnitude;
        }

        /// <summary>The largest difference between two profiles of one mesh, in mesh units; infinity when they differ in kind.</summary>
        public float Difference(WeaponProfile other)
        {
            if (other.Axis != Axis || other.Extents.Length != Extents.Length) return float.PositiveInfinity;
            float worst = Mathf.Max(Mathf.Abs(other.Min - Min), Mathf.Abs(other.Max - Max));
            for (int i = 0; i < Extents.Length; i++) worst = Mathf.Max(worst, Mathf.Abs(other.Extents[i] - Extents[i]));
            return worst;
        }
    }
}
